site_name: NordHHub Documentation
theme:
  name: material

nav:
  - Home: index.md
  - Introduction: docs/introduction.md
  - Model Elements:
      - Data Loading: docs/data_loading.md
      - Model Builder: docs/model_builder.md
      - Reporting: docs/reporting.md
  - Usage:
      - Running the Model: docs/run_model.md
      - Results: docs/results.md
