site_name: Documentation

theme:
  name: material

nav:
  - Home: index.md
  - Introduction: introduction.md

  - Model:
      - Overview: model/model-overview.md
      - Math formulation: model/math-formulation.md

  - Model Elements:
      - Data Loading: load_module.md
      - Model Builder: model_builder.md
      - Reporting: reporting.md

  - Input Files:
      - Nodes: input_files/nodes.md
      - Arcs: input_files/arcs.md
      - Scalars / Other parameters: input_files/others.md

  - Usage:
      - Running the Model: run_model.md
      - Results: results.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
