site_name: Documentation
theme:
  name: material

nav:
  - Home: index.md
  - Introduction: docs/introduction.md
  - Model Elements:
      - Data Loading: docs/load_module.md
      - Model Builder: docs/model_builder.md
      - Reporting: docs/reporting.md
  - Input Files:
      - Nodes: input_files/nodes.md
      - Arces: input_files/arcs.md
  - Usage:
      - Running the Model: docs/run_model.md
      - Results: docs/results.md
